[package]
name = "pulsar_web"
description = "fast and reliable web framework"
license = "Unlicense"
license-file = "LICENSE"
version = "0.1.1"
edition = "2021"
exclude = ["src/main.rs"]

[dependencies]
async-std = "1.13.0"
coloredpp = "0.3.0"
